### ISSUE TITLE
 Not in scope: ‘ifThenElse’

### ISSUE THREAD

**Issue by hath995** [mightybyte/monad-challenges#32] opened 2016-01-23 08:26 UTC
``` haskell
{-# LANGUAGE MonadComprehensions #-}
{-# LANGUAGE RebindableSyntax  #-}

module Set1 where

import MCPrelude

data Maybe a = Nothing | Just a
instance Show a => Show (Maybe a) where
    show (Just a) = "Just " ++ show a
    show Nothing = "Nothing"

lookupMay :: Eq k => k -> [(k, j)] -> Maybe j
lookupMay a [] = Nothing
lookupMay a ((b,c) : xs) = if a == b then Just b else lookupMay a xs

```

throws that the error  Not in scope: ‘ifThenElse’ when I try to compile the file. Not sure what to do with that. The function works when I try it in an un edited ghci instance but not with those pragmas I think.

**Comment by emberian** [comment] 2016-01-23 12:15
I don't know the cause of the error, but one workaround is to use guards instead.

**Comment by mightybyte** [comment] 2016-01-23 14:57
Thanks for the report!  I just pushed a fix.  It should work now.  If it's still not fixed, then reopen this issue.

**Closed as completed by mightybyte** 2016-01-23 14:57 UTC

**Comment by csdrane** [comment] 2016-01-23 21:08
Meanwhile I thought this was intentional :-/
